import React from 'react';
import CarouselPage from './CarouselPage';

const MainPage = () => {
    return (
        <div className='pt-20 ml-[20vw] bg-slate-100 px-5'>
            <CarouselPage></CarouselPage>
            <h1>shop Main page</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet atque quod unde illum repellendus ex dolorum asperiores, nisi totam quis a quae laudantium voluptas quidem recusandae tenetur quaerat, libero quam?
            Illum soluta deserunt vel laudantium accusantium, laboriosam ullam voluptatibus voluptates. Voluptatem non illo eos error. Alias, nulla possimus blanditiis cumque porro accusantium tenetur modi id, sequi aspernatur officia asperiores harum!
            Sequi corporis sit ipsum. Dicta repellat molestiae, sequi ut et architecto necessitatibus totam reiciendis porro, nulla, pariatur atque. Libero quisquam quasi molestias quod fugit ea facere eum vel neque quaerat?
            At similique quam molestiae ut? Placeat harum, fugiat numquam voluptatibus aliquid iure non earum consequatur, nulla tempore soluta accusamus possimus totam consequuntur magnam iste necessitatibus eligendi reprehenderit rem vel impedit.
            Blanditiis tenetur nam repellendus eum sint cumque id delectus consectetur iste atque dignissimos ullam qui aperiam animi dicta, aliquam rerum maxime in dolorem nihil! Quos minus praesentium ipsum voluptates aperiam.
            Voluptatem voluptatum cupiditate officiis recusandae itaque aperiam harum, dolor, magnam consectetur quod consequuntur eos assumenda officia? Obcaecati magnam, magni assumenda optio velit enim voluptas itaque veritatis voluptatum distinctio ipsam officia!
            Dolorem doloremque cum sit quia corporis ipsam recusandae est ea fuga porro ullam unde, enim tempora dolorum maiores praesentium distinctio culpa totam architecto ipsum inventore illo, numquam eos. Doloribus, optio.
            Voluptatibus saepe accusantium, nobis corrupti error dolor assumenda iste? Quas iste aliquid et debitis harum magni! Aliquid, minima similique illum necessitatibus accusamus tempora officiis quo cumque voluptates cupiditate earum perspiciatis.
            Modi, totam. Tempora dicta inventore nulla numquam natus doloribus enim dolorem in? Quod, quam saepe? Aperiam velit doloribus eligendi totam natus veritatis quaerat odio officia pariatur tempore, temporibus, accusamus est.
            Dicta, temporibus beatae. Optio natus cum eveniet, ducimus quos sint quisquam quas fuga iusto deserunt laboriosam, alias reiciendis, aut ea asperiores maiores eos aperiam. Id natus iusto harum minima velit.
            Laborum dolores vitae dicta eligendi facilis, illo laboriosam deleniti architecto! Odio repellat voluptatibus minus eaque aliquid repudiandae esse, aperiam sint delectus, exercitationem hic. Aperiam, magni! Est voluptatem quia sint dolor!
            Error blanditiis, quasi atque distinctio sit praesentium quaerat, aliquid nobis eos ut vero beatae cumque totam earum nulla sint quia? Deserunt necessitatibus iure harum obcaecati aperiam in modi voluptatibus numquam.
            Rerum recusandae sequi consequuntur illum aspernatur adipisci placeat officia exercitationem modi explicabo vero rem, in fugiat perspiciatis consequatur quas soluta atque sint nisi eos eaque numquam totam accusamus! Possimus, sed!
            Voluptatibus placeat dignissimos ea sed molestias, iusto a veniam excepturi quam, cupiditate porro ipsa optio, harum magnam accusamus temporibus eius obcaecati perspiciatis. Vero eum ipsam, eveniet tenetur molestias voluptatibus impedit.
            Saepe eos fuga voluptatum rerum repellendus numquam beatae animi molestiae consequatur quam dignissimos quod laudantium sint ut assumenda, facere necessitatibus dolor consectetur! Quasi, odit similique culpa facilis error ab sequi.
            Cupiditate, cum unde. Tempore distinctio suscipit facere animi voluptatum ab cupiditate hic veritatis sunt commodi ipsam consequatur iure quisquam et quos aliquam dolore, illum esse cumque! Magnam neque dolores labore.
            Architecto delectus commodi, nostrum temporibus assumenda aspernatur quidem earum excepturi reprehenderit numquam voluptatem totam pariatur eum ipsum quaerat nulla similique praesentium unde quos repellat ut! Voluptas delectus blanditiis nisi facere?
            Quas dolorum a numquam consequatur sapiente deserunt! Eius nesciunt quae obcaecati accusamus vel sunt maiores libero perspiciatis aut molestiae odio voluptas earum illum recusandae at eum, id blanditiis exercitationem ducimus.
            Magni voluptatibus quae repudiandae nulla facere temporibus itaque nisi, neque facilis saepe ipsa dolore reiciendis sint doloribus accusamus! Odio est dolorum nesciunt voluptatibus laudantium repellendus sit ipsa eveniet aliquid fuga!
            Accusantium delectus iusto impedit optio consectetur animi rem, repellat tenetur culpa et adipisci cum odio obcaecati corporis deleniti eligendi placeat exercitationem quae hic at eius distinctio eum voluptas. Minima, unde.
            Maxime exercitationem eos ipsam praesentium, tenetur nobis beatae quis consectetur, magni vero, saepe minus quibusdam iusto quaerat magnam quod. Doloribus minima magni error unde vel esse perferendis at corporis animi?
            Modi facere nam perspiciatis aperiam fugiat voluptatum perferendis nisi, ipsa error quaerat omnis, laudantium magni provident consequuntur recusandae excepturi, repudiandae voluptatem fuga incidunt sit? Odit amet eveniet aliquid tenetur libero!
            Alias minus exercitationem aut corporis modi nulla eius soluta illo minima voluptas, at delectus sequi saepe laboriosam. Nulla vitae aut, porro sint placeat natus mollitia assumenda dolor est maxime fuga?
            Repellat, omnis? Deleniti hic minima voluptas nihil, tenetur delectus dolore. Ipsum quod nisi modi qui cupiditate voluptatibus ut facilis. Assumenda aliquam tenetur, earum ratione aperiam modi vel optio omnis ex.
            Sunt quod delectus impedit voluptas qui, natus ipsum hic labore quae doloribus officia dicta modi accusantium quam exercitationem fugit temporibus totam consequuntur dolorum commodi iure et optio fuga! Nulla, ex.
            Sit labore sint sequi excepturi quibusdam pariatur eligendi dolor quas quasi mollitia, ipsum animi nostrum earum molestias omnis praesentium, nihil nesciunt quaerat soluta expedita, odio optio inventore tenetur exercitationem? Assumenda?
            Voluptatibus optio unde eos quam deserunt, magni laboriosam consequatur facere assumenda odio impedit, molestiae, minus ab ad hic ipsum? Sed suscipit ipsam deleniti qui doloremque facere itaque dolore dolores amet?
            Voluptates odio ut incidunt iure velit iusto sunt dignissimos quaerat laudantium, quia pariatur impedit aliquid illo id dicta quo reprehenderit sapiente, cum autem esse consequuntur? Ipsa nulla eaque qui repudiandae.
            Nemo reiciendis iure, nesciunt provident quis eum veniam, quod aliquid porro eveniet expedita incidunt ullam facilis. Aperiam, eum enim velit at rem, eligendi aliquid laudantium voluptatibus quas, cumque expedita mollitia.
            Ipsa a sunt assumenda non, illum quia consequuntur dolorum veritatis ipsam provident. Voluptatibus fuga nesciunt officia eaque ea tempore, non quaerat tenetur? Consectetur sequi quae illum molestiae, libero quasi. Quibusdam?
            Laboriosam totam culpa quisquam ut labore vitae ab recusandae, veniam nostrum voluptatum blanditiis reprehenderit maiores nesciunt illo voluptates numquam. At ut illo laboriosam numquam adipisci, perspiciatis quisquam corporis corrupti voluptate.
            Placeat voluptatem nostrum, illum sit deserunt adipisci facere in soluta labore ut sed ipsam, tenetur eveniet minus officiis veritatis ullam, unde perferendis. Odit harum ea ipsum, pariatur saepe illum dolorem.
            Quasi, magni consequatur minus voluptatum impedit esse recusandae. Ut aspernatur qui atque dignissimos voluptate ab veniam placeat amet esse accusantium dicta, ipsa eos reiciendis ipsam quae similique modi sed sint!
            Deleniti debitis nesciunt nulla atque cumque in placeat excepturi perspiciatis? Nobis saepe natus praesentium corrupti soluta voluptate, voluptatum deserunt repellendus ex reiciendis. Pariatur nisi eaque quo amet recusandae ex neque.
            Provident aut delectus expedita officia sapiente, ullam nulla vitae cumque iure tempore optio itaque vel. Dolores molestias odit dignissimos consequatur nihil! Nesciunt quasi, culpa architecto aut hic necessitatibus incidunt odit.
            Totam sunt debitis numquam, veniam quo incidunt at exercitationem voluptas dicta, fugiat eos possimus eligendi, adipisci sequi. Facere quisquam hic sunt perferendis sed, nam incidunt qui labore dolores fugit dignissimos!
            Illum maiores tempora ipsa incidunt hic natus, dignissimos consequuntur voluptatem accusantium velit, aliquid quis iusto voluptatum, nostrum ipsum. Laboriosam quis quasi mollitia, animi voluptates recusandae eveniet officiis et neque error.
            Veritatis soluta voluptate atque, perspiciatis earum inventore, sequi nisi, dicta incidunt rem odit voluptatum sed laborum itaque pariatur? Minus accusamus optio fuga omnis est? Numquam, commodi alias. Qui, nostrum impedit.
            Harum quaerat esse commodi magni temporibus quasi ratione, aspernatur, rem eum minus vel optio autem voluptas corrupti architecto. Similique enim unde temporibus animi optio accusamus officia omnis, perferendis repellendus consequuntur?
            Enim voluptate quas omnis aut, voluptatum beatae facere sapiente impedit et aliquam culpa, accusantium cumque eos debitis dignissimos. Ullam, eligendi magni itaque nulla perferendis a reprehenderit quae minima debitis est.
            Quis doloribus officia corporis expedita quos perferendis eveniet veniam non inventore minima, qui eos voluptatum. Repellendus, commodi? Explicabo voluptates, dolor corrupti sunt, quos animi, aperiam vitae error hic suscipit quae.
            Eligendi, dicta ab beatae aut eveniet nam voluptatem aliquid unde earum iste quia obcaecati omnis dolore vitae adipisci? Eaque, consectetur quasi. Voluptatibus doloribus alias, totam perferendis mollitia nesciunt a optio.
            Maiores ipsa, animi nulla a, minima est laboriosam, totam excepturi ratione nesciunt cumque earum quia. Tenetur earum, similique ad eveniet consequuntur officia. Ratione, voluptatum eius cum sapiente tenetur voluptatem ipsum?
            In architecto mollitia laborum asperiores assumenda vel laboriosam. Incidunt minima at velit dolores sapiente aliquid doloribus nisi tempore veniam, nesciunt vero facilis deserunt reprehenderit dignissimos, quidem molestias eligendi odio nemo!
            Ex suscipit voluptatum similique excepturi? Odit deserunt corporis accusantium veritatis reprehenderit nobis animi quaerat consectetur repellendus quia ducimus sunt necessitatibus odio dignissimos, ut similique. Soluta ducimus mollitia beatae at? Optio.
            Odio voluptas odit pariatur aspernatur at ipsam doloribus ipsa aperiam reprehenderit ab necessitatibus delectus sequi, officia voluptates animi, similique dolorum architecto rem quis eius eligendi sit ad recusandae! Rem, nulla.
            Quam vel labore dicta dolorum totam rerum similique natus aspernatur nam, officiis praesentium odit delectus est harum possimus, quasi soluta ad autem corrupti. Obcaecati natus vel dolorem iste temporibus est!
            Numquam temporibus saepe sequi consequatur placeat porro, odio unde voluptas commodi quaerat reiciendis aperiam nostrum delectus sint natus molestias asperiores! Quaerat eum iure eveniet delectus maiores facilis dolorem nobis. Necessitatibus!
            Cupiditate sequi atque praesentium temporibus exercitationem aperiam similique dolore ex doloremque dicta alias dolorem corporis repellat tempora adipisci nemo excepturi, voluptatem aliquid ipsa eum tenetur ipsam totam, vitae perspiciatis? Harum.
            Quibusdam neque error odio ea perferendis eligendi quo temporibus consequuntur maxime magni vel, quod deleniti consequatur atque nesciunt corporis ullam earum unde inventore, dignissimos rem? Quibusdam ducimus incidunt porro neque.
            Doloribus aliquam quisquam numquam, nulla nemo quidem beatae omnis vero nobis provident maiores tempora voluptates ea, velit quae illum dolor commodi! Eligendi laudantium reprehenderit aliquam, similique error perferendis eius quas.
            Dicta, eveniet molestiae? Dolorem est voluptas sit enim minus veritatis provident ut dolor praesentium recusandae suscipit ad, esse dolore nesciunt voluptatem repellendus atque neque facilis laborum minima delectus aperiam alias!
            Vel illo alias voluptas, in officiis doloremque magni libero doloribus unde dolorum sapiente inventore, quia distinctio odio consequuntur impedit neque est omnis voluptates laboriosam pariatur. Nostrum earum ex non minima!
            Laborum voluptates debitis minima pariatur alias, cupiditate tempore, at iusto facilis magni eum nostrum ipsum odio cum dolorem eaque reprehenderit recusandae repudiandae eligendi, doloremque mollitia incidunt blanditiis suscipit? Corporis, quia!
            Dicta suscipit, distinctio asperiores maiores a nemo nostrum in cumque quaerat. Autem tenetur dolorum recusandae cupiditate excepturi doloremque itaque doloribus saepe quos. Fugiat vitae nam pariatur quisquam, ea odio impedit.
            Quia, laborum. Eveniet sequi inventore corporis, beatae rerum porro. Beatae vel nesciunt quaerat? Inventore corrupti voluptates perferendis atque ex. Natus mollitia atque odio ratione deleniti? Error quisquam aspernatur vitae porro?
            Aperiam perspiciatis commodi autem, inventore asperiores possimus maiores blanditiis dolores illo minima at. Eligendi neque amet corrupti tenetur placeat, veritatis eum? Impedit cumque quo eum a similique. Perspiciatis, tenetur quo?
            Exercitationem doloremque nostrum temporibus unde similique, debitis dolorem beatae optio inventore at iure animi officiis neque delectus. Repellendus, repellat eveniet beatae suscipit mollitia iusto nesciunt, minima, cupiditate error fugit placeat!
            Eos dolorum maiores dolorem repudiandae expedita, pariatur ratione doloremque facilis at fugiat aliquam accusantium iusto corporis. Aut, iste hic neque nam quas cupiditate quisquam! Voluptas excepturi repellat dolorem expedita beatae.
            Culpa maxime, nihil deleniti ex voluptatem est, ea totam beatae voluptatum sunt nisi assumenda voluptas porro nobis reprehenderit! Possimus illum ullam optio consequuntur obcaecati dolorem adipisci non odio vero saepe.
            Porro iusto consequatur numquam ipsam. Dolores enim dolore placeat fugiat magni vel? Fugit hic explicabo maiores at mollitia nemo fuga non. Aliquid eaque consequuntur vero laboriosam quidem. Obcaecati, architecto rem.
            Nam distinctio sint dignissimos consequatur rerum vero dolores quam, voluptas, modi autem, ullam possimus? Provident atque suscipit, minus cupiditate beatae placeat saepe qui error est assumenda repudiandae itaque in at?
            Nihil doloremque totam sequi officiis culpa atque eum accusamus, aspernatur ab quos. Distinctio, dolorem cum! Ratione ad porro architecto amet consequuntur reprehenderit reiciendis quod, veniam nemo veritatis, a perspiciatis deleniti.
            Consequuntur hic esse officiis dolorem sapiente, voluptatem culpa incidunt, nesciunt doloribus laborum, eligendi explicabo molestiae? Quae eveniet natus, sed at, quidem possimus corporis voluptatem, ab incidunt debitis pariatur doloremque praesentium.
            Earum molestias neque eos odit, debitis, natus hic incidunt harum enim quas ut vel commodi maiores expedita? Ullam ipsam eos, iste consequuntur, quis consequatur laborum mollitia architecto deleniti quo labore.
            Dolore sapiente laudantium doloremque ab libero, non dolorum facere provident fuga assumenda in placeat quaerat dolorem ad odio atque quas mollitia ratione eum architecto officia? Aspernatur doloremque animi voluptates ad?
            Omnis corporis quod officiis possimus maiores consequuntur inventore ipsam fugiat cum laboriosam. Nihil ea culpa fugiat praesentium nobis facere autem? Iste excepturi illum suscipit ducimus aspernatur incidunt architecto recusandae praesentium.
            Accusamus quia repellat, impedit iste consequatur aperiam, laboriosam voluptates neque tempore, commodi fuga recusandae excepturi dolorum officiis deserunt labore ducimus necessitatibus quod! Nemo, repudiandae recusandae. Atque necessitatibus ducimus quidem eius.
            Libero impedit cum sunt laborum voluptas rem aut! Quos ducimus nisi voluptatum sunt qui vitae perspiciatis dolorem! Voluptatibus vitae, magni unde doloremque aut dicta natus commodi ipsum autem consectetur ullam!
            Eveniet sapiente ex, dolores reprehenderit suscipit accusantium perspiciatis fuga recusandae autem, ipsa placeat doloribus sequi eius numquam sunt enim. Illo placeat corporis hic, culpa rerum quisquam perspiciatis soluta veritatis amet.
            Obcaecati provident, nihil, ipsa totam reiciendis at tempore neque ducimus omnis, rerum soluta quasi aliquid quisquam sit officiis porro illum numquam ipsum. Officiis quibusdam sed minima repellat alias veritatis commodi.
            Hic facere quaerat, porro officia excepturi saepe alias? Corrupti, non. Sapiente expedita temporibus quidem animi cum fuga illo molestiae. Asperiores impedit obcaecati recusandae vel sed corporis exercitationem explicabo doloremque reiciendis.
            Reiciendis sequi fuga distinctio labore impedit quibusdam excepturi minus non omnis, aut quisquam quis molestiae necessitatibus facilis! Quo sint sapiente recusandae, labore optio eaque ab natus reiciendis cupiditate asperiores voluptatum!
            Nemo velit assumenda dignissimos iste reprehenderit sint animi tempora libero! Dolore totam nulla soluta repellendus, illo, laborum dolorem odit molestiae cupiditate distinctio neque eum asperiores voluptates autem at recusandae aut.
            Qui quo deleniti ea, ex doloremque harum nostrum esse itaque reprehenderit cumque labore sequi tempore? Modi officiis, totam saepe eligendi, nobis, doloremque quae sit odio voluptate veritatis excepturi sed facere!
            Perspiciatis corporis doloremque asperiores nihil soluta ipsum accusamus assumenda sed? Corporis quidem, reprehenderit animi rem earum incidunt libero enim voluptatem placeat iure quisquam delectus reiciendis temporibus aspernatur corrupti ex dolor.
            Maxime officiis veniam necessitatibus voluptates aut, ipsum vero minima ea, maiores et illo similique recusandae voluptatum minus nisi odio repudiandae cum eius quam a, adipisci vitae veritatis amet voluptas. Voluptas?
            Culpa minima voluptas porro soluta cupiditate provident illum temporibus consequuntur id quisquam, quibusdam vel maiores quidem, laboriosam officiis? Aperiam unde iure labore blanditiis nostrum expedita facilis nihil deserunt accusantium commodi.
            Dolor architecto esse enim quis debitis quo, delectus quod obcaecati eos minus! Eligendi sunt nostrum doloremque vel modi eveniet natus odit at, iusto, numquam animi in. Facilis sit laborum excepturi.
            Maiores cum ex deleniti sit, necessitatibus molestias. Obcaecati repellat, reiciendis placeat harum praesentium fugiat vitae eaque architecto soluta necessitatibus consectetur officia rem. Consequatur explicabo, atque quaerat sunt odit porro id.
            Voluptates aspernatur a repellendus mollitia reiciendis exercitationem autem ea quisquam velit expedita id neque iure, magni consectetur in doloribus suscipit ipsum consequuntur dolorem, pariatur nam! Eius iure quae sunt ipsa.
            Officia doloribus perferendis ducimus? Delectus illum eaque debitis rem quam consectetur eum quo, reiciendis iure repellat sed minima quis adipisci excepturi consequatur iusto porro consequuntur rerum, quas accusantium magnam nobis?
            Suscipit quis saepe maiores qui! Ab aspernatur eligendi quam pariatur expedita quod explicabo, et voluptates reiciendis vitae labore vel, officia tenetur quaerat eaque esse earum excepturi. Blanditiis sint provident placeat?
            Tempore modi ipsa dolorum aliquid eos assumenda, amet consectetur fugiat reiciendis dolore, cum accusamus deleniti natus aperiam eligendi doloremque error velit! Exercitationem dolores ea quae non enim blanditiis voluptatum sit.
            Maxime ratione minus quas error, voluptate dolorum natus doloremque nisi maiores fugit a facilis architecto sed. Officia sunt sequi pariatur at soluta nulla dignissimos quaerat. Voluptatem voluptatum sapiente laboriosam rerum.
            Eius aliquam nihil voluptatibus in dolorem aspernatur labore fugit repellendus facere optio dicta ad error, soluta doloribus sequi minus iusto quas cumque illo provident mollitia maxime esse eligendi laudantium! Sequi!
            Quisquam iure et, dignissimos inventore quibusdam explicabo fuga aliquam? Rerum ducimus quos eos, vel, in corrupti iusto esse provident sequi soluta animi perferendis et. Odio ipsum mollitia ab omnis quas.
            Esse doloremque at assumenda tenetur nemo officiis dicta, enim iusto dolores sed quia ut earum quam delectus tempore debitis dolor impedit eligendi incidunt quibusdam. Quisquam, voluptatem. Quas, asperiores. Minima, itaque.
            Omnis, sint distinctio? Fugit ipsa aspernatur commodi asperiores beatae nisi, similique ad assumenda temporibus officiis laboriosam nobis odio maiores nemo aliquam sapiente sint odit vel nostrum neque eos minus dicta?
            Nemo beatae totam repellat sunt aliquam excepturi a voluptatibus ex eaque modi, harum exercitationem maiores laboriosam iste hic odio natus perferendis dignissimos molestias debitis culpa reprehenderit nesciunt? Sapiente, reprehenderit consequatur.
            Voluptate perferendis adipisci odio deleniti, nam alias saepe praesentium perspiciatis similique reprehenderit! Eligendi animi, sapiente nesciunt in veniam omnis at! Repellat, vitae quod molestiae hic voluptatum laboriosam? Repellendus, exercitationem unde.
            Ipsam ut distinctio nam ex. Neque omnis animi laudantium labore nisi similique mollitia, nulla, recusandae voluptate iusto nihil commodi esse dolorem quas aperiam? Enim nisi odit, id libero impedit consequuntur.
            Laudantium placeat minima aspernatur perferendis natus odit laboriosam tempora incidunt non, sint cupiditate cum ad beatae enim ullam autem, deleniti recusandae sapiente voluptatem quia dolorum at. Nemo, impedit vitae? Dicta?
            Quasi sint error suscipit incidunt pariatur? Beatae, laudantium. Minus recusandae dicta vitae! Ut non, ducimus vitae ipsum facilis id libero! Dolorum, numquam repudiandae blanditiis nesciunt voluptatibus asperiores adipisci saepe neque.
            Error fugit nostrum tempore vitae totam, ratione quas deserunt, perspiciatis est itaque mollitia. Magni nam, provident ipsam officia placeat labore dicta repellat? Blanditiis impedit quaerat molestiae vitae. Voluptas, vel id!
            Impedit voluptatum officia aliquid blanditiis, rerum, culpa odio esse ab architecto, ut fugit necessitatibus deserunt eaque modi minima molestiae earum ipsa! Vitae cupiditate earum voluptas ut voluptate maxime, perspiciatis facilis!
            Optio numquam, officiis fuga cumque nulla a. Dolores optio sequi quisquam, quod eum, ex eaque distinctio dolorum minus quia obcaecati! Atque, repellendus? Qui praesentium dolorem modi, ullam earum in aut?
            Obcaecati in numquam amet doloribus laborum esse, facere mollitia fugiat aliquam, reprehenderit dolores aperiam neque veniam sed perferendis libero impedit fuga cum exercitationem sint minima est quibusdam. Voluptate, laudantium ipsam.
            A blanditiis numquam et. Obcaecati quod neque voluptatum pariatur blanditiis sequi reprehenderit vitae, esse iure accusantium voluptatem voluptas temporibus illo maiores ratione ex quo rerum omnis modi nam similique architecto.
            At cum iure autem cupiditate sit nobis, fugit blanditiis cumque minus modi aspernatur numquam! Nihil corporis ut ratione obcaecati quisquam beatae corrupti autem eligendi quia cumque? Placeat, dolor ipsum? Alias.</p>
        </div>
    );
};

export default MainPage;